name: Publish npm package to gitea
on:
  release:
    types: [published]
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download yarn
        run: |
          curl -fsSL -o /usr/local/bin/yarn https://github.com/yarnpkg/yarn/releases/download/v1.22.21/yarn-1.22.21.js
          chmod +x /usr/local/bin/yarn
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: Run yarn build
        run: |
          yarn build
      - name: Configure git.vdb.to npm registry
        run: |
          npm config set registry https://git.vdb.to/api/packages/cerc-io/npm/
      - name: Authenticate to git.vdb.to registry
        run: |
          npm config set -- '//git.vdb.to/api/packages/cerc-io/npm/:_authToken' "${{ secrets.CICD_PUBLISH_TOKEN }}"
      - name: npm publish
        run: |
          npm publish
