name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  sdk_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout laconicd
        uses: actions/checkout@v3
        with:
          path: "./laconicd/"
          repository: cerc-io/laconicd
          fetch-depth: 0
          ref: main
      - name: Environment
        run: ls -tlh && env
      - name: build registry-cli container
        run: docker build -t cerc/laconic-registry-cli:local-test --build-arg CERC_NPM_URL=https://git.vdb.to/api/packages/cerc-io/npm/ --build-arg CERC_NPM_AUTH_TOKEN=${{ secrets.GITEA_PUBLISH_TOKEN }} .
      - name: build containers scripts
        working-directory: laconicd/tests/sdk_tests
        run: ./build-laconicd-container.sh
      - name: start laconicd container
        working-directory: laconicd/tests/sdk_tests
        run: docker compose up laconicd -d

      - name: Run registry-cli demo commands in registry-cli container
        run : |
          laconicd_key=$( docker compose exec laconicd echo y | docker compose exec laconicd laconicd keys export mykey --unarmored-hex --unsafe )
          ./create-config.sh $laconicd_key
          echo ./config.yml
          ls -tla
      - name: stop containers
        working-directory: laconicd/tests/sdk_tests
        run: docker compose down

